import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased p-2`}
      >
        <div className="pb-2 mb-4 border-gradient font-bold text-lg underline">
          {" "}
          <ul>
            <li>
              <Link href="/ssr">Go to /ssr</Link>
            </li>
            <li>
              <Link href="/rsc">Go to /rsc</Link>
            </li>
          </ul>
        </div>
        {children}
      </body>
    </html>
  );
}
